### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ehawkvu** [s-gannon/meetingbot#3]
This project is missing a LICENSE file.

**Comment by ejyager00** [comment]
Hello @ehawkvu so I needed a bit more time to test and
apparently it did not fix my problems, still have those vulkan errors
and system freezes.

Anyway so I've decided to ditch chrome for palemoon, and it
seems to work fine for most web tasks (even this shit-hub interface
sort of works)
Modern Firefox has turned into piece of shit software (by using rust)
so I don't even consider supporting their company and software.
Because we are X11 gang here we have it least some other choice
to bloatyfox, palememe does not work on wayland.
One of the notable features of palememe that I admire
is that it compiles fast (maybe even faster than webkit)
Feel free to add it to your community repo if you deem
so worthy, my purpose was to just let you know that this
exists.

**Comment by s-gannon** [comment]
Hello @ehawkvu so I needed a bit more time to test and
apparently it did not fix my problems, still have those vulkan errors
and system freezes.

Anyway so I've decided to ditch chrome for palemoon, and it
seems to work fine for most web tasks (even this shit-hub interface
sort of works)
Modern Firefox has turned into piece of shit software (by using rust)
so I don't even consider supporting their company and software.
Because we are X11 gang here we have it least some other choice
to bloatyfox, palememe does not work on wayland.
One of the notable features of palememe that I admire
is that it compiles fast (maybe even faster than webkit)
Feel free to add it to your community repo if you deem
so worthy, my purpose was to just let you know that this
exists.

**Comment by s-gannon** [comment]
I don't know how to add a license after the fact, so for the time being we're just going to say it's exclusive copyright
